# Generated by Django 2.2.1 on 2019-05-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('edicao', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('editora', models.CharField(max_length=50)),
            ],
        ),
    ]
