# Generated by Django 2.2.1 on 2019-05-29 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0003_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('email', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
                ('telefone', models.CharField(max_length=255)),
                ('fk_endereco_pk', models.IntegerField()),
                ('senha', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('cod_cliente', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('valor_total', models.FloatField()),
                ('cod_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fk_cliente_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('numero_edicao', models.IntegerField()),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_reserva', models.DateField()),
                ('fk_cliente_cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.Cliente')),
                ('kf_livro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.Livro')),
            ],
        ),
        migrations.DeleteModel(
            name='cdastro_livros',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='compra',
            name='fk_livro_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.Livro'),
        ),
    ]
