# Generated by Django 2.2.1 on 2019-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0006_auto_20190617_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='enter/imagens/%y/%/%D'),
        ),
    ]
